name: Google Calendar
version: "1.0.1"
slug: gcalendar
description: Zobrazí Google Kalendář jako dlaždici v Home Assistantu.
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
panel_icon: mdi:calendar
panel_title: Google Kalendář
ingress: false
webui: "http://[HOST]:[PORT:8000]"
ports:
  8000/tcp: 8000
