name: Google Calendar
version: "1.0.18"
slug: gcalendar
description: Zobrazí Google Kalendář jako dlaždici v Home Assistantu.
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
options:
  certfile: /data/gcalendar/cert.pem
  keyfile: /data/gcalendar/privkey.pem
schema:
  certfile: str
  keyfile: str
ports:
  8000/tcp: 8000
webui: "https://[HOST]:[PORT:8000]"
host_network: true
